import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'rw';

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

const translations: Translations = {
    en: {
        // Header
        'blockchain': 'Blockchain',
        'blockchain_ledger': 'Blockchain Ledger',
        'account': 'Account',
        'logout': 'Logout',
        'switch_language': 'Switch Language',
        'search_placeholder': 'Search anything...',
        'offline_status': 'You are offline. All changes are saved locally and will sync when online.',
        'pending_changes_msg': '{count} pending change{s} waiting to sync',
        'sync_now': 'Sync Now',
        'syncing': 'Syncing...',

        // Navigation
        'dashboard_label': 'Dashboard',
        'store_label': 'Products Store',
        'sold_label': 'Products Sold',
        'restored_label': 'Products Restored',
        'trash_label': 'Trash',
        'branches_label': 'Manage Branch',
        'employees_label': 'Manage Employees',
        'reports_label': 'Reports',
        'welcome_back': 'Welcome back,',
        'need_help': 'Need help? Contact support 24/7.',
        'need_help_for': 'I need help for ',
        'sign_out': 'Sign Out',
        'user': 'User',
        'smart_manager': 'Smart Manager',

        // Dashboard
        'dashboard_title': 'Dashboard',
        'inventory_console': 'Inventory Console',
        'real_time_analytics': 'Real-time Stock Value & Profit Analytics',
        'system_status': 'System Status',
        'live_connection': 'Live Connection',
        'dashboard_context': 'Dashboard context:',
        'weekly_stock_value': 'Weekly Stock Value',
        'monthly_stock_value': 'Monthly Stock Value',
        'yearly_stock_value': 'Yearly Stock Value',
        'total_net_profit': 'Total Net Profit',
        'net_profit_subtitle': 'Profit from all sold products after calculated loss',
        'current_stock_value': 'Current Stock Value',
        'total_stock_value_subtitle': 'Total value of all products in stock',
        'total_loss': 'Total Loss',
        'total_loss_subtitle': 'Total loss from all sold products',
        'weekly_activity': 'Weekly Activity',
        'monthly_activity': 'Monthly Activity',
        'yearly_activity': 'Yearly Activity',
        'stock_highlights': 'Stock Highlights',
        'most_stocked': 'MOST STOCKED PRODUCT',
        'least_stocked': 'LEAST STOCKED PRODUCT',
        'never_updated': 'Never Updated',
        'in_stock': 'In Stock',
        'pending_actions': 'Pending Actions',
        'sold': 'Sold',
        'restored': 'Restored',
        'deleted': 'Deleted',
        'low_stock': 'Low Stock',
        'out_of_stock': 'Out of Stock',
        'avg_stock': 'Avg Stock',
        'total_products': 'Total Products',
        'categories': 'Categories',
        'models': 'Models',
        'all_products': 'All products',
        'unique_categories': 'Unique categories',
        'unique_models': 'Unique models',
        'added_today': 'Added Today',
        'added_this_week': 'Added This Week',
        'added_this_month': 'Added This Month',
        'updated_today': 'Updated Today',
        'new_today': 'New today',
        'this_week': 'This week',
        'this_month': 'This month',
        'updated_at': 'Updated today',
        'today': 'Today',
        'no_sales_data': 'No sales data available for this period',
        'no_activity_data': 'No activity data available',
        'yearly_investment': 'Yearly Investment',
        'total_confirmed_investment': 'Total Confirmed Investment',
        'confirmed_stock': 'Confirmed stock',
        'awaiting_approval': 'Awaiting approval',
        'total_sold': 'Total sold',
        'returned': 'Returned',
        'in_trash': 'In trash',
        'max_10_units': '≤10 units',
        '0_units': '0 units',
        'per_product': 'Per product',
        'total_current_value': 'Total Current Value',
        'current_stock': 'Current Stock',
        'inventory_count': 'Inventory Count',
        'units': 'Units',

        // Profile
        'profile_title': 'My Profile',
        'edit_profile': 'Edit Profile',
        'save': 'Save',
        'save_changes': 'Save Changes',
        'saving': 'Saving...',
        'cancel': 'Cancel',
        'personal_details': 'Personal Details',
        'business_info': 'Business Information',
        'address_settings': 'Address Settings',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'gender': 'Gender',
        'male': 'Male',
        'female': 'Female',
        'select_gender': 'Select Gender',
        'phone': 'Phone',
        'district': 'District',
        'sector': 'Sector',
        'cell': 'Cell',
        'village': 'Village',
        'active': 'Active',
        'pending': 'Pending',
        'role': 'Role',
        'intro': 'Intro',
        'admin_account': 'Administrator Account',
        'staff_account': 'Staff Member',
        'works_at': 'Works at',
        'lives_in': 'Lives in',
        'no_phone': 'No phone',
        'edit_details': 'Edit Details',
        'not_set': 'Not set',
        'business_name': 'Business Name',
        'settings': 'Settings',
        'email_address': 'Email Address',
        'email': 'Email',
        'enter_email': 'Enter email address',
        'update_email_desc': 'Update your email request',
        'email_label': 'Email Address',
        'email_placeholder': 'yourname@gmail.com',
        'phone_placeholder': '07X XXX XXXX',
        'password_label': 'Password',
        'change_password_desc': 'Change your security password',
        'pending_changes': 'pending changes',
        'verify_identity': 'Verify Your Identity',
        'create_new_password': 'Create New Password',
        'current_password': 'Current Password',
        'enter_current_password': 'Enter your current password',
        'new_password': 'New Password',
        'enter_new_password': 'Enter new password',
        'confirm_password': 'Confirm New Password',
        'confirm_new_password_placeholder': 'Confirm your new password',
        'passwords_dont_match': 'Passwords do not match.',
        'password_min_length': 'Password must be at least 6 characters.',
        'continue_button': 'Continue',
        'update_password': 'Update Password',
        'update_email': 'Update Email',
        'reset_password': 'Reset Password',
        'delete_account': 'Delete Account',
        'delete_confirm_desc': 'This action is permanent and cannot be undone. All your data will be deleted.',
        'delete_my_account': 'Delete My Account',
        'edit_cover_photo': 'Edit Cover Photo',
        'image_selected': 'Image Selected',
        'uploading': 'Uploading...',
        'upload_failed': 'Upload Failed',
        'profile_updated_success': 'Profile updated successfully!',
        'profile_save_failed': 'Failed to save profile. Please try again.',
        'logged_out': 'Logged Out',
        'signed_out_success': 'Signed out successfully.',
        'logout_failed': 'Failed to log out.',
        'verified': 'Verified ✓',
        'password_verified': 'Current password correct. Set new one.',
        'password_update_failed': 'Failed to update password.',
        'email_sent': 'Sent',
        'check_email_reset': 'Check your email for reset link.',
        'send_reset_failed': 'Failed to send reset email.',
        'account_deleted': 'Account permanently deleted.',
        'relogin_needed': 'Re-login Needed',
        'relogin_to_delete': 'Please sign in again before deleting account.',
        'email_update_failed': 'Failed to update email.',
        'email_in_use': 'This email is already in use.',
        'relogin_required': 'Please log out and log in again.',
        'login_to_view_profile': 'Please log in to view your profile.',
        'enter_current_password_error': 'Please enter your current password.',
        'stock_management': 'Stock Management',
        'low_stock_threshold': 'Low Stock Threshold',
        'out_of_stock_threshold': 'Out of Stock Threshold',
        'settings_label': 'Settings',
        'settings_updated_success': 'Settings updated successfully!',
        'saved_locally_offline': 'Saved locally (offline) – will sync when online',
        'error_saving_settings': 'Failed to save settings. Please try again.',
        'admin_only_settings': 'Only administrators can access business settings.',
        'low_stock_desc': 'Products with quantities equal to or below this value will be marked as "Low Stock".',
        'out_of_stock_desc': 'Products with quantities equal to or below this value will be marked as "Out of Stock".',

        // Store / Products
        'products_store': 'Products Store',
        'all_products_in_stock': 'All products currently in stock',
        'search_products': 'Search products...',
        'search_placeholder_products': 'Search name, category, model...',
        'add_product': 'Add Product',
        'add_new_product': 'Add New Product',
        'edit_product_title': 'Edit Product',
        'update_product': 'Update Product',
        'update_product_desc': 'Update product details and see changes in real-time',
        'product_details': 'Product Details',
        'sell_product': 'Sell Product',
        'confirm_sale': 'Confirm Sale',
        'delete_product_confirm': 'Delete Product?',
        'requires_admin_confirm': 'Requires admin confirmation',
        'auto_confirmed': 'Auto-confirmed',
        'live_preview': 'Live Preview',
        'product_identity': 'Product Identity',
        'no_name': 'No Name',
        'no_category': 'No Category',
        'entered_amount': 'Entered Amount',
        'calculated_unit_cost': 'Calculated Unit Cost',
        'total_investment_value': 'Total Investment Value',
        'fill_all_required': 'Please fill all required fields to record.',
        'fill_all_required_error': 'Fill all required fields correctly',
        'ready_for_recording': 'Product ready for recording to inventory.',
        'recording': 'Recording...',
        'record_product': 'Record Product',
        'product_added_success': 'Product added successfully',
        'product_add_failed': 'Failed to add product',
        'product_updated_success': 'Product updated',
        'available': 'Available',
        'quantity_to_sell': 'Quantity to Sell',
        'selling_price_per_unit': 'Selling Price (per unit)',
        'return_deadline': 'Return Deadline (optional)',
        'profit_loss_preview': 'Profit & Loss Preview',
        'profit_per_unit': 'Profit per Unit',
        'total_revenue': 'Total Revenue',
        'total_profit_loss': 'Total Profit/Loss',
        'complete_sale': 'Complete Sale',
        'confirm_sale_desc': 'Are you sure you want to confirm this sale?',
        'yes_confirm_sale': 'Yes, Confirm Sale',
        'change_confirmation_status': 'Change Confirmation Status',
        'confirm_product_question': 'Are you sure you want to confirm this product?',
        'unconfirm_product_question': 'Are you sure you want to unconfirm this product?',
        'confirm_change': 'Confirm Change',
        'close': 'Close',
        'permanent_action_desc': 'This action cannot be undone.',
        'expected_profit': 'Expected Profit',
        'sell': 'Sell',
        'update': 'Update',
        'delete': 'Delete',
        'deleting': 'Deleting...',
        'branch': 'Branch',
        'unassigned': 'Unassigned',
        'no_branch_assigned': 'No Branch Assigned',
        'product_name': 'Product Name',
        'category_label': 'Category',
        'all_categories': 'All Categories',
        'model_label': 'Model',
        'cost_price': 'Cost Price',
        'selling_price': 'Selling Price',
        'quantity_label': 'Quantity',
        'total_value': 'Total Value',
        'status_label': 'Status',
        'actions': 'Actions',
        'confirm': 'Confirm',
        'confirmed': 'Confirmed',
        'export': 'Export',
        'weekly_stats': 'Weekly Stats',
        'monthly_stats': 'Monthly Stats',
        'yearly_stats': 'Yearly Stats',
        'cost_configuration': 'Cost Configuration',
        'cost_per_unit': 'Cost Per Unit',
        'total_bulk_cost': 'Total Bulk Cost',
        'select_branch': 'Select Branch',
        'select_branch_for': 'Select branch for',
        'unit': 'Unit',
        'pieces': 'Piece (pc)',
        'bag': 'Bag',
        'crate': 'Crate',
        'liter': 'Liter (L)',
        'kilograms': 'Kilogram (kg)',
        'gram': 'Gram (g)',
        'milliliter': 'Milliliter (mL)',
        'sack': 'Sack',
        'bottle': 'Bottle',
        'pack': 'Pack',
        'box': 'Box',
        'meter': 'Meter (m)',
        'added_date': 'Added Date',
        'confirmation': 'Confirmation',
        'confirmed_only': 'Confirmed Only',
        'unconfirmed_only': 'Unconfirmed Only',
        'min_value': 'Min Value',
        'max_value': 'Max Value',
        'min_qty': 'Min Qty',
        'max_qty': 'Max Qty',
        'all': 'All',
        'pick_date': 'Pick a date',
        'clear_date': 'Clear Date',
        'optional': 'optional',
        'enter_placeholder': 'Enter...',
        'invalid_sale': 'Invalid sale',
        'sold_success_msg': 'Sold successfully',
        'deleted_success': 'Deleted',
        'status_updated': 'Status updated',
        'back_online_syncing': 'Back Online – Syncing...',
        'offline_changes_sync_later': 'Offline – Changes will sync later',
        'failed_load_branches': 'Failed to load branches',
        'using_cached_data': 'Using cached branch data',
        'all_branches': 'All Branches',
        'products_in': 'Products in',
        'your_branch': 'Your Branch',
        'unknown_branch': 'Unknown Branch',
        'no_branch': 'No Branch',
        'no_products_found_filters': 'No products found matching your filters.',
        'no_products_found': 'No products found.',
        'cannot_set_past_date': 'Cannot set a past date',
        'cannot_sell_unconfirmed': 'You cannot sell an unconfirmed product.',

        // Auth - UPDATED & IMPROVED MESSAGES
        'welcome_back_login': 'Welcome back',
        'enter_details_login': 'Please enter your details to sign in.',
        'forgot_password': 'Forgot password?',
        'sign_in_button': 'Sign in',
        'or_divider': 'Or',
        'google_login': 'Google',
        'dont_have_account': "Don't have an account?",
        'sign_up_link': 'Sign up',
        'create_account_title': 'Create an account',
        'business_details_step': 'Enter your business details to get started.',
        'personal_details_step': 'Complete your personal information.',
        'upload_logo': 'Upload Logo',
        'next_step': 'Next Step',
        'back_button': 'Back',
        'create_account_button': 'Create Account',
        'already_have_account': 'Already have an account?',
        'password_placeholder': 'Enter your password',

        // NEW AUTH ERROR MESSAGES (used in updated AuthContext)
        'wrong_password': 'Wrong password.',
        'invalid_email': 'Please enter a valid email address.',
        'too_many_attempts': 'Too many failed attempts. Please try again later.',
        'network_error': 'Network error. Please check your connection.',
        'other': 'Other',
        'select': 'Select',
        'business_name_min': 'Business name must be at least 2 characters',
        'district_required': 'Please enter your district',
        'sector_required': 'Please enter your sector',
        'cell_required': 'Please enter your cell',
        'village_required': 'Please enter your village',
        'first_name_min': 'First name must be at least 2 characters',
        'last_name_min': 'Last name must be at least 2 characters',
        'phone_required': 'Please enter a valid phone number',
        'account_created_success': 'Account created! You are using free mode. Trial ends in 1 month.',
        'image_size_error': 'Image size must be less than 5MB',
        'business_name_exists': 'This business name is already registered.',
        'email_exists': 'This email is already registered.',
        'phone_exists': 'This phone number is already registered.',
        'profile_image_upload_failed': 'Failed to upload profile image.',
        'user_not_found_create': 'User not found. You can create an account for free (first month in test mode).',
        'user_inactive_wait_admin': 'Your account is pending approval. Please wait for your business admin to approve.',
        'business_inactive_wait_central': 'Your business is not activated yet. Please wait for central admin approval.',

        // Keep old keys for backward compatibility (optional)
        'invalid_credentials': 'Incorrect email or password.',
        'business_inactive_error': 'Your business is not active. Please wait for central admin to approve your business.',
        'user_inactive_error': 'Your account is not active. Please wait for business admin to approve your account.',

        // Reports
        'business_report_title': 'Business Report',
        'business_report_desc': 'Complete overview of store, sold, restored, and deleted products',
        'export_report': 'Export Report',
        'export_excel': 'Export to Excel',
        'export_pdf': 'Export to PDF',
        'report_context': 'Report context',
        'gross_profit': 'Gross Profit',
        'net_profit': 'Net Profit',
        'total_store_value': 'Store Value',
        'no_data_available': 'No report data available.',
        'total_value_processed': 'Total Value Processed',
        'no_branch_assigned_msg': 'You are not assigned to any branch.',
        'contact_admin_access': 'Contact your admin to get access.',
        'no_data_match': 'No data match',
        'unit_cost_label': 'Unit Cost',
        'profit_label': 'Profit',
        'sold_deleted_date_label': 'Sold/Deleted Date',

        // Inventory (Sold/Restored/Deleted)
        'sold_products_title': 'Sold Products',
        'sold_products_desc': 'View and manage sold products',
        'restored_products_title': 'Restored Products',
        'restored_products': 'Restored Products',
        'restored_products_desc': 'View and sell restored products',
        'deleted_products_title': 'Deleted Products (Trash)',
        'deleted_products': 'Deleted Products',
        'deleted_products_desc': 'View and manage deleted products',
        'daily_income': 'Daily Income',
        'weekly_income': 'Weekly Income',
        'monthly_income': 'Monthly Income',
        'yearly_income': 'Yearly Income',
        'weekly_restored_value': 'Weekly Restored Value',
        'monthly_restored_value': 'Monthly Restored Value',
        'yearly_restored_value': 'Yearly Restored Value',
        'restore_selected': 'Restore Selected',
        'restore_product': 'Restore Product',
        'permanent_delete': 'Delete Permanently',
        'delete_selected': 'Delete Selected',
        'sell_restored': 'Sell Restored Product',
        'return_product': 'Return Product',
        'sale_record_deleted': 'Sale record deleted',
        'restored_successfully': 'Restored successfully',
        'deleted_permanently': 'Deleted permanently',
        'reason_label': 'Reason',
        'delete_reason': 'Delete Reason',
        'restore_reason': 'Restore Reason',
        'income': 'Income',
        'value': 'Value',
        'generated_profit': 'Profit',
        'received_amount': 'Total Received',
        'actual_unit_cost': 'Actual Unit Cost',
        'available_stock': 'Available in restored stock',
        'quantity_to_restore': 'Quantity to Restore',
        'restore_confirm_question': 'Restore this product back to store?',
        'delete_confirm_question': 'Permanently delete this product?',
        'bulk_restore_confirm': 'Restore selected products?',
        'bulk_delete_confirm': 'Delete selected products?',
        'no_sold_products': 'No sold products found.',
        'no_restored_products': 'No restored products found.',
        'no_deleted_products': 'No deleted products found.',
        'displaying_sales_for': 'Displaying sales for:',
        'showing_restored_products_for': 'Showing restored products for:',
        'showing_restored_for': 'Showing restored products for:',
        'restoring_from_sale': 'Restoring from sale',
        'quantity_restore': 'Quantity to Restore',
        'restore_qty_placeholder': 'Enter quantity to restore',
        'restore_reason_placeholder': 'Enter reason for restoration',
        'confirm_restore': 'Confirm Restoration',
        'restored_products_in': 'Restored products in',
        'all_restored_products_admin': 'All restored products across all branches',
        'deleted_products_from': 'Deleted products from',
        'all_deleted_products_admin': 'All deleted products across all branches',
        'no_deleted_products_found': 'No deleted products found.',
        'deleted_product_details': 'Deleted Product Details',
        'restore_confirm_msg': 'Are you sure you want to restore',
        'restore_selected_products_q': 'Restore Selected Products?',
        'restore_selected_confirm_msg': 'Are you sure you want to restore the selected products?',
        'permanently_delete_product_q': 'Permanently Delete Product?',
        'permanent_delete_warning': 'Are you sure you want to permanently delete',
        'no_sold_products_date': 'No sold products found for this date.',
        'sold_product_details': 'Sold Product Details',
        'restore_sold_product': 'Restore Sold Product',
        'no_restored_products_date': 'No restored products found for this date.',
        'restored_product_details': 'Restored Product Details',
        'cost_price_base': 'Cost Price (Base)',
        'selling_price_base': 'Selling Price (Base)',
        'sell_restored_product': 'Sell Restored Product',
        'available_restored_stock': 'Available in restored stock',
        'quantity_sell': 'Quantity to Sell',
        'quantity_placeholder': 'Enter quantity...',
        'selling_price_placeholder': 'Enter price...',

        // Admin (Employees/Branches)
        'manage_employees_title': 'Manage Employees',
        'manage_employees': 'Manage Employees',
        'manage_employees_desc': 'Create and manage staff accounts',
        'employees': 'Employees',
        'create_manage_staff': 'Create and manage staff members for your business.',
        'add_employee': 'Add Employee',
        'photo': 'Photo',
        'created_at': 'Created',
        'assign_branch': 'Assign Branch',
        'assigning': 'Assigning...',
        'assign_branch_desc': 'Select a branch to assign this employee to.',
        'create_employee_title': 'Create New Employee',
        'create_new_employee': 'Create New Employee',
        'create_employee': 'Create Employee',
        'creating': 'Creating...',
        'update_employee_title': 'Update Employee',
        'update_employee': 'Update Employee',
        'employee_details_title': 'Employee Details',
        'employee_details': 'Employee Details',
        'delete_employee_q': 'Delete Employee?',
        'delete_employee_confirm': 'Delete Employee?',
        'delete_employee_warning': 'This action cannot be undone. This employee will be permanently deleted.',
        'delete_selected_employees_q': 'Delete Selected Employees?',
        'delete_multiple_employees_warning': '{count} employees will be permanently deleted.',
        'name': 'Name',
        'required_fields_error': 'Please fill all required fields',
        'employee_updated_success': 'Employee updated successfully',
        'offline_warning': 'You are offline – changes will sync automatically when back online',
        'default_password_msg': 'Default password will be',

        'manage_branches_title': 'Manage Branches',
        'manage_branches': 'Manage Branches',
        'manage_branches_desc': 'Create, update, or delete branches',
        'branches': 'Branches',
        'branches_desc': 'View and manage all your branches.',
        'add_branch': 'Add Branch',
        'branch_name': 'Branch Name',
        'example_branch_name': 'e.g. Kigali Main',
        'example_district': 'e.g. Gasabo',
        'create_branch_title': 'Create New Branch',
        'create_new_branch': 'Create New Branch',
        'create_branch': 'Create Branch',
        'create_branch_desc': 'Fill in the details for the new branch.',
        'update_branch_title': 'Update Branch',
        'update_branch': 'Update Branch',
        'update_branch_desc': 'Edit the branch information.',
        'branch_details_title': 'Branch Details',
        'branch_details': 'Branch Details',
        'delete_branch_q': 'Delete Branch?',
        'delete_branch_confirm': 'Delete Branch?',
        'delete_branch_warning': 'This action cannot be undone. This branch will be permanently deleted.',
        'delete_selected_branches_q': 'Delete Selected Branches?',
        'delete_multiple_branches_warning': '{count} branches will be permanently deleted.',
        'offline_mode': 'Offline – changes will sync later',
        'default_password_notice': 'Default password will be',
        'fill_all_fields_error': 'Please fill all fields',
        'branch_created_success': 'Branch created successfully',
        'branch_updated_success': 'Branch updated successfully',
        'branch_removed_success': 'Branch removed successfully',
        'employee_created': 'Employee created successfully',
        'employee_updated': 'Employee updated successfully',
        'employee_deleted': 'Employee deleted successfully',
        'no_employees_found': 'No employees found.',
        'search_employees': 'Search employees...',
        'no_branches_found': 'No branches found.',
        'search_branches': 'Search branches...',

        // Shared
        'loading': 'Loading...',
        'error': 'Error',
        'success': 'Success',
        'yes': 'Yes',
        'no': 'No',
        'account_deactivated': 'Your account has been deactivated. Please contact your administrator.',
        'business_inactive': 'Your business account is inactive. Please contact system administration.',
        'switch_theme': 'Switch Theme',
        'light_mode': 'Light Mode',
        'dark_mode': 'Dark Mode',
        'language': 'Language',
        'theme': 'Theme',
        'english': 'English',
        'kinyarwanda': 'Kinyarwanda',
        'access_denied': 'Access Denied',
        'checking_details': 'Checking details...',
        'sold_products': 'Sold Products',
        'sold_products_from': 'Sold products from',
        'all_sold_products_admin': 'All sold products across all branches',
        'income_label': 'Daily Income',
        'total_received': 'Total Received',
        'profit_loss': 'Profit/Loss',
        'sold_date': 'Sold Date',
        'sold_qty': 'Sold Qty',
        'search_sold_products': 'Search sold products...',
        'search_restored_products': 'Search restored products...',
        'total_cost_value': 'Total Cost Value',
        'restored_date': 'Restored Date',
        'restored_qty': 'Restored Qty',
        'search_deleted_products': 'Search deleted products...',
        'deleted_date': 'Deleted Date',
        'delete_permanently': 'Delete Permanently',
        'restore_product_q': 'Restore Product?',
        'restoring': 'Restoring...',
        'expiry_date': 'Expiry Date',
        'days_remaining': 'Days Remaining',
        'expired_product': 'Expired Product',
        'expired_products': 'Expired Products',
        'never_expires': 'Never Expires',
        'expires_soon': 'Expires Soon',
        'days_left': 'days left',

        // Landing Page - Navigation
        'nav_features': 'Features',
        'nav_services': 'Services',
        'nav_pricing': 'Pricing',
        'nav_testimonials': 'Testimonials',
        'nav_partners': 'Partners',
        'nav_login': 'Login',
        'nav_get_started': 'Get Started',

        // Landing Page - Hero
        'hero_title_1': 'The intuitive inventory platform for',
        'hero_title_highlight': 'fast-growing businesses',
        'hero_subtitle': "Streamline your inventory with SmartStock's smart tracking, multi-branch support, automated reports, and powerful analytics platform.",
        'hero_cta_primary': 'Get started free',
        'hero_cta_secondary': 'Talk to Sales',
        'hero_feature_1': 'Track inventory in minutes',
        'hero_feature_2': 'Keep data secure',
        'hero_feature_3': 'Manage your team',
        'hero_rating': '5-STAR RATING',
        'hero_no_card': 'no credit card required',
        'hero_daily_sales': 'Daily Sales',

        // Landing Page - Stats
        'stat_happy_clients': 'Happy Clients',
        'stat_business_accounts': 'Business Accounts',
        'stat_trusted_customers': 'Trusted Customers',
        'stat_success_rate': 'Success Rate',

        // Landing Page - Features
        'features_title': 'Powerful Features for Your Business',
        'features_subtitle': 'Everything you need to manage inventory efficiently and scale your business.',
        'feature_inventory_title': 'Inventory Management',
        'feature_inventory_desc': 'Track inventory, manage stock levels, and monitor product movements in real-time with powerful analytics.',
        'feature_branch_title': 'Branch & Employee Management',
        'feature_branch_desc': 'Manage employees, assign roles, and control access across multiple branches seamlessly.',
        'feature_reports_title': 'Automated Reports',
        'feature_reports_desc': 'Get detailed insights on sales, profits, and inventory performance with automated reporting.',
        'feature_alerts_title': 'Real-Time Alerts',
        'feature_alerts_desc': 'Receive instant notifications when stock levels are low or when action is required.',
        'feature_security_title': 'Enterprise Security',
        'feature_security_desc': 'Bank-level encryption and security to keep your business data safe and compliant.',
        'feature_backup_title': 'Cloud Backup',
        'feature_backup_desc': 'Automatic cloud backups ensure your data is always safe and accessible from anywhere.',

        // Landing Page - Services
        'services_title': 'Comprehensive Services',
        'services_subtitle': 'Built for modern businesses that demand excellence and reliability.',
        'service_tracking_title': 'Product Tracking',
        'service_tracking_desc': 'Monitor every product movement with detailed tracking and history logs.',
        'service_multi_branch_title': 'Multi-Branch Support',
        'service_multi_branch_desc': 'Manage unlimited branches and locations from a single dashboard.',
        'service_analytics_title': 'Smart Analytics',
        'service_analytics_desc': 'Get actionable insights with AI-powered analytics and forecasting.',
        'service_collaboration_title': 'Team Collaboration',
        'service_collaboration_desc': 'Enable your team to work together with role-based access control.',

        // Landing Page - Testimonials
        'testimonials_label': 'Testimonials',
        'testimonials_title': 'Trusted by leaders',
        'testimonials_subtitle': 'from various industries',
        'testimonials_desc': 'Learn why professionals trust our solutions to complete their customer journeys.',
        'testimonials_cta': 'Read Success Stories',

        // Landing Page - Pricing
        'pricing_title': 'Simple, Transparent Pricing',
        'pricing_subtitle': 'Choose the perfect plan for your business. Start free, upgrade anytime.',
        'pricing_best_value': 'Best Value',
        'pricing_pay_now': 'Pay Now',
        'pricing_duration_month': '/month',
        'pricing_duration_year': '/year',
        'pricing_duration_forever': '/forever',

        // Plans
        'plan_free_name': 'Free Plan',
        'plan_free_desc': '(Test Mode – First Month Only)',
        'plan_monthly_name': 'Monthly Plan',
        'plan_monthly_desc': '(For Active Businesses)',
        'plan_annually_name': 'Annually Plan',
        'plan_annually_desc': '(Best Value – Save 25%)',
        'plan_forever_name': 'Forever Plan',
        'plan_forever_desc': 'Lifetime License – One Time Payment',

        // Plan Features
        'feature_all_unlocked': 'All SmartStock features unlocked',
        'feature_unlimited_products': 'Unlimited Products & Sales',
        'feature_unlimited_employees': 'Unlimited Employees & Branches',
        'feature_multi_branch': 'Multi-Branch Management',
        'feature_advanced_reports': 'Advanced Reports & Analytics',
        'feature_returns': 'Returns & Trash Recovery',
        'feature_monitoring': 'Admin Transaction Monitoring',
        'feature_support': 'System Updates & Support',

        // Landing Page - CTA Bottom
        'cta_title': 'Ready to Transform Your Business?',
        'cta_subtitle': 'Join hundreds of businesses already using SmartStock to streamline their inventory management.',
        'cta_start_free': 'Start Free Trial',
        'cta_learn_more': 'Learn more',

        // Landing Page - Partners
        'partners_title_1': 'Grow your business as a',
        'partners_title_highlight': 'SmartStock',
        'partners_title_2': 'partner',
        'partners_desc': "Let's work together. Join our community of partners to better serve mutual customers and grow your business.",
        'partners_apply': 'Apply now',

        // Landing Page - Footer
        'footer_desc': 'Your trusted partner in inventory management solutions for businesses.',
        'footer_product': 'Product',
        'footer_company': 'Company',
        'footer_stay_updated': 'Stay Updated',
        'footer_whatsapp_desc': 'Join our WhatsApp channel for the latest updates and news.',
        'footer_join_whatsapp': 'Join WhatsApp Channel',
        'footer_about': 'About Us',
        'footer_contact': 'Contact',
        'footer_support': 'Support',
        'footer_rights': '© 2025 SmartStock. All rights reserved. Developed by the SmartStock Developer Team.',
        'footer_dev_team': 'Join our Developer Team to be part of us.',
        'footer_dev_link': 'Developer Team',
        'fab_help': 'Need help? Chat with us!',
        'add_expiry_date': 'Add Expiry Date (Optional)',
        'subscription_expired_title': 'Subscription Expired',
        'subscription_expired_message': 'Your subscription plan has expired. You need to renew your subscription to access your dashboard.',
        'subscription_expired_link': 'Go to Home Page to Renew',

        // Payment Dialog
        'plan': 'Plan',
        'locale': 'en-US',
        'select_payment_method': 'Select Payment Method',
        'pay_amount_for': 'Pay',
        'plan_monthly': 'Monthly Plan',
        'plan_annually': 'Annually Plan',
        'plan_forever': 'Forever Plan',
        'plan_free': 'Free Plan',
        'for_plan': 'for',
        'mtn_momo': 'MTN Mobile Money',
        'airtel_money': 'Airtel Money',
        'bank_transfer_bk': 'Bank Transfer (BK)',
        'finding_account': 'Finding account...',
        'continue': 'Continue',
        'verify_account_details': 'Verify Account Details',
        'verify_account_desc': 'Enter your account credentials to identify the business for this payment.',
        'password': 'Password',
        'back': 'Back',
        'verifying': 'Verifying...',
        'verify_next': 'Verify & Next',
        'or': 'Or',
        'continue_with_google': 'Continue with Google',
        'complete_payment': 'Complete Payment',
        'account_status': 'Account Status',
        'account_active_msg': 'Your account is currently active.',
        'send_money_desc': 'Send money to the details below.',
        'subscription_ends_on': 'Subscription ends on',
        'days_remaining_lower': 'days remaining',
        'continue_to_dashboard': 'Continue to Dashboard',
        'phone_number': 'Phone Number',
        'account_number': 'Account Number',
        'recipient': 'Recipient',
        'your_phone_placeholder': 'Enter your phone number',
        'your_account_placeholder': 'Enter your account number',
        'your_name_label': 'Your Name',
        'your_name_placeholder': 'Enter your full name',
        'processing': 'Processing...',
        'confirm_payment': 'Confirm Payment',
        'need_help_whatsapp': 'Need Help? Chat on WhatsApp',
        'payment_submitted': 'Payment Submitted!',
        'payment_received_msg': 'We have received your payment request.',
        'waiting_for_approval': 'Waiting for Approval',
        'admin_verification_msg': 'Your subscription will be active as soon as an administrator verifies your payment. This usually takes 15-30 minutes.',
        'close_wait': 'Close & Wait',

        // Toasts
        'copied_to_clipboard': 'Copied to clipboard',
        'user_record_not_found': 'User record not found',
        'no_business_linked': 'No business linked to this account',
        'business_details_not_found': 'Business details not found',
        'failed_fetch_business': 'Failed to fetch business info',
        'enter_email_password': 'Please enter email and password',
        'account_verified': 'Account verified!',
        'invalid_email_password': 'Invalid email or password',
        'verification_failed': 'Verification failed',
        'google_verification_failed': 'Google verification failed',
        'session_expired_verify': 'Session expired. Please verify account locally.',
        'payment_failed_try_again': 'Payment failed. Please try again.',
    },
    rw: {
        // Header
        'blockchain': 'Ibyakozwe',
        'blockchain_ledger': 'risite yibyakozwe',
        'account': 'Konti yanjye',
        'logout': 'Sohoka',
        'switch_language': 'Hindura Ururimi',
        'search_placeholder': 'Shakisha ikintu cyose...',
        'offline_status': 'Uri gukora utari kuri interineti. Impinduka zose zibitswe kuri telefoni.',
        'pending_changes_msg': 'Hari impinduka {count} zitegereje kubikwa',
        'sync_now': 'Ohereza',
        'syncing': 'Kohereza...',

        // Navigation
        'dashboard_label': 'Incamake',
        'store_label': 'Ububiko',
        'sold_label': 'Byagurishijwe',
        'restored_label': 'Byagaruwe',
        'trash_label': 'Ibyasibwe',
        'branches_label': 'Amashami',
        'employees_label': 'Abakozi',
        'reports_label': 'Raporo',
        'welcome_back': 'Muraho neza,',
        'need_help': 'Ukeneye ubufasha? Twandikire igihe cyose.',
        'need_help_for': 'Nkeneye ubufasha kuri ',
        'sign_out': 'Sohoka',
        'user': 'Ukoresha',
        'smart_manager': 'Smart Manager',

        // Dashboard
        'dashboard_title': 'Incamake',
        'inventory_console': 'Imicungire y\'ububiko',
        'real_time_analytics': 'Isesengura ry\'agaciro k\'ibicuruzwa n\'inyungu',
        'system_status': 'Imiterere ya sisitemu',
        'live_connection': 'Ihuza rirahari',
        'dashboard_context': 'Imiterere y\'incamake:',
        'weekly_stock_value': 'Agaciro k\'ibicuruzwa ku cyumweru',
        'monthly_stock_value': 'Agaciro k\'ibicuruzwa ku kwezi',
        'yearly_stock_value': 'Agaciro k\'ibicuruzwa ku mwaka',
        'total_net_profit': 'Inyungu ',
        'net_profit_subtitle': 'Inyungu ivuye mu bicuruzwa byagurishijwe nyuma yo gukuramo igihombo',
        'current_stock_value': 'Agaciro k\'ibicuruzwa bisigaye m\'ububiko',
        'total_stock_value_subtitle': 'Agaciro kose k\'ibicuruzwa biri mu bubiko',
        'total_loss': 'Igihombo cyose',
        'total_loss_subtitle': 'Igihombo cyose cyavuye mu bicuruzwa byagurishijwe',
        'weekly_activity': 'Ibikorwa by\'icyumweru',
        'monthly_activity': 'Ibikorwa by\'ukwezi',
        'yearly_activity': 'Ibikorwa by\'umwaka',
        'stock_highlights': 'Ibyingenzi mu bubiko',
        'most_stocked': 'IGICURUZWA CYINSHI',
        'least_stocked': 'IGICURUZWA GIKE',
        'never_updated': 'Bitigeze bihindurwa',
        'in_stock': 'Bihari',
        'pending_actions': 'Ibitegerejwe',
        'sold': 'Byagurishijwe',
        'restored': 'Byagaruwe',
        'deleted': 'Byasibwe',
        'low_stock': 'Ibike cyane',
        'out_of_stock': 'Byashize',
        'avg_stock': 'Impuzandengo',
        'total_products': 'Ibicuruzwa byose',
        'categories': 'Ibyiciro',
        'models': 'Ubwoko',
        'all_products': 'Ibicuruzwa byose',
        'unique_categories': 'Ibyiciro byihariye',
        'unique_models': 'Ubwoko bwihariye',
        'added_today': 'byongewewo uyu munsi',
        'added_this_week': 'Byongewewo iki cyumweru',
        'added_this_month': 'Byongewewo uku kwezi',
        'updated_today': 'Byahinduwe uyu munsi',
        'new_today': 'Bishya uyu munsi',
        'this_week': 'Iki cyumweru',
        'this_month': 'Uku kwezi',
        'updated_at': 'Byahinduwe uyu munsi',
        'today': 'Uyu munsi',
        'no_sales_data': 'Nta makuru y\'ibigurishijwe ahari muri iki gihe',
        'no_activity_data': 'Nta makuru y\'ibikorwa ahari',
        'yearly_investment': 'Ishoramari ry\'Umwaka',
        'total_confirmed_investment': 'Ishoramari ryose ryemejwe',
        'confirmed_stock': 'Ububiko bwemejwe',
        'awaiting_approval': 'Birategereje kwemezwa',
        'total_sold': 'Ibyagurishijwe',
        'returned': 'Byagaruwe',
        'in_trash': 'ibyasibwe',
        'max_10_units': '≤10',
        '0_units': '0',
        'per_product': 'Ku gicuruzwa',
        'total_current_value': 'Agaciro k\'ibihari byose',
        'current_stock': 'Ububiko buhari',
        'inventory_count': 'Umubare w\'ibiri mu bubiko',
        'units': 'Imibare',

        // Profile
        'profile_title': 'Umwirondoro wanjye',
        'edit_profile': 'Hindura Umwirondoro',
        'save': 'Bika',
        'save_changes': 'Bika Impinduka',
        'saving': 'Birabikwa...',
        'cancel': 'Reka',
        'personal_details': 'Ibiranga umuntu',
        'business_info': 'Ibiranga ubucuruzi',
        'address_settings': 'Ibiranga aho uba',
        'first_name': 'Izina rya mbere',
        'last_name': 'Izina rya kabiri',
        'gender': 'Igitsina',
        'male': 'Gabo',
        'female': 'Gore',
        'select_gender': 'Hitamo Igitsina',
        'phone': 'Terefone',
        'district': 'Akarere',
        'sector': 'Umurenge',
        'cell': 'Akagari',
        'village': 'Umudugudu',
        'active': 'Birakora',
        'pending': 'Birategerejwe',
        'role': 'Inshingano',
        'intro': 'Ahabanza',
        'admin_account': 'Konti y\'uyiyobora',
        'staff_account': 'Umukozi',
        'works_at': 'Akora muri',
        'lives_in': 'Atuye mu',
        'no_phone': 'Nta terefone ihari',
        'edit_details': 'Hindura ibiranga umuntu',
        'not_set': 'Ntabwo byashyizwemo',
        'business_name': 'Izina ry\'ubucuruzi',
        'settings': 'Igenamiterere',
        'enter_email': 'Shyiramo imeri',
        'update_email_desc': 'Hindura imeri yawe',
        'email_address': 'Imeri',
        'email': 'Imeri',
        'email_label': 'Imeri',
        'email_placeholder': 'imeri_yanyu@gmail.com',
        'phone_placeholder': '07X XXX XXXX',
        'password_label': 'Ijambo ry\'ibanga',
        'change_password_desc': 'Hindura ijambo ry\'ibanga ryawe',
        'pending_changes': 'ibyahinduwe bitarabikwa',
        'verify_identity': 'Erekana ko ari wowe',
        'create_new_password': 'Shyiramo ijambo ry\'ibanga rishya',
        'current_password': 'Ijambo ry\'ibanga wakoreshaga',
        'enter_current_password': 'Shyiramo ijambo ry\'ibanga wakoreshaga',
        'new_password': 'Ijambo ry\'ibanga rishya',
        'enter_new_password': 'Shyiramo ijambo ry\'ibanga rishya',
        'confirm_password': 'Emeza ijambo ry\'ibanga rishya',
        'confirm_new_password_placeholder': 'Subiramo ijambo ry\'ibanga rishya',
        'passwords_dont_match': 'Amagambo y\'ibanga ntabwo ahuye.',
        'password_min_length': 'Ijambo ry\'ibanga rigomba kugira imigombane nibura 6.',
        'continue_button': 'Komeza',
        'update_password': 'Hindura ijambo ry\'ibanga',
        'update_email': 'Hindura Imeri',
        'reset_password': 'Siba ijambo ry\'ibanga',
        'delete_account': 'Siba konti',
        'delete_confirm_desc': 'Ibi bikorwa ntibishobora gusubirwamo. Amakuru yawe yose azasibwa.',
        'delete_my_account': 'Siba konti yanjye',
        'edit_cover_photo': 'Hindura Ifoto yo hejuru',
        'image_selected': 'Ifoto yahiswemo',
        'uploading': 'Birashyirwaho...',
        'upload_failed': 'Kwineza byanze',
        'profile_updated_success': 'Umwirondoro wahinduwe neza!',
        'profile_save_failed': 'Gukina umwirondoro byanze. Ongera ugerageze.',
        'logged_out': 'Wasohotse',
        'signed_out_success': 'Wasohotse neza.',
        'logout_failed': 'Gusohoka byanze.',
        'verified': 'Byemejwe ✓',
        'password_verified': 'Ijambo ry\'ibanga rihuye. Shyiraho rishya.',
        'password_update_failed': 'Guhindura ijambo ry\'ibanga byanze.',
        'email_sent': 'Byagiye',
        'check_email_reset': 'Reba imeri yawe ukanze ahabugenewe.',
        'send_reset_failed': 'Kohereza imeri byanze.',
        'account_deleted': 'Konti yasibwe burundu.',
        'relogin_needed': 'Ongera Winjire',
        'relogin_to_delete': 'Banza usohoke wongere winjire mbere yo gusiba konti.',
        'email_update_failed': 'Guhindura imeri byanze.',
        'email_in_use': 'Iyi imeri irakoreshwa.',
        'relogin_required': 'Sohoka wongere winjire.',
        'login_to_view_profile': 'Injira kugirango urebe umwirondoro wawe.',
        'enter_current_password_error': 'Banza ushyiremo ijambo ry\'ibanga wakoreshanga',
        'stock_management': 'Imicungire y\'Ububiko',
        'low_stock_threshold': 'Ingano y\'ibicuruzwa bike',
        'out_of_stock_threshold': 'Ingano y\'ibicuruzwa byashize',
        'settings_label': 'Igenamiterere',
        'settings_updated_success': 'Igenamiterere ryahinduwe neza!',
        'saved_locally_offline': 'Bibitswe kuri telefoni (offline) – bizongerwa kuri interineti niboneka',
        'error_saving_settings': 'Guhindura igenamiterere byanze. Ongera ugerageze.',
        'admin_only_settings': 'Abayobozi gusa nibo bemerewe guhindura igenamiterere ry\'ubucuruzi.',
        'low_stock_desc': 'Ibicuruzwa bifite ingano ingana cyangwa iri munsi y\'iyi mibare bizashyirwa mu cyiciro cy\' "Ibike cyane".',
        'out_of_stock_desc': 'Ibicuruzwa bifite ingano ingana cyangwa iri munsi y\'iyi mibare bizashyirwa mu cyiciro cy\' "Byashize".',

        // Store / Products
        'products_store': 'Ububiko',
        'all_products_in_stock': 'Ibicuruzwa byose biri mu bubiko',
        'search_products': 'Shakisha ibicuruzwa...',
        'search_placeholder_products': 'Shakisha izina, icyiciro, ubwoko...',
        'add_product': 'Ongeramo igicuruzwa',
        'add_new_product': 'Ongeramo igicuruzwa gishya',
        'edit_product_title': 'Hindura igicuruzwa',
        'update_product': 'Hindura igicuruzwa',
        'update_product_desc': 'Hindura ibiranga igicuruzwa unarebe uko bihinduka ako kanya',
        'product_details': 'Ibiranga igicuruzwa',
        'sell_product': 'Gurisha igicuruzwa',
        'confirm_sale': 'Emeza igurisha',
        'delete_product_confirm': 'Siba igicuruzwa?',
        'requires_admin_confirm': 'Bisaba kwemezwa n\'umuyobozi',
        'auto_confirmed': 'Byemejwe ako kanya',
        'live_preview': 'Reba uko bimeze',
        'product_identity': 'Umwirondoro w\'igicuruzwa',
        'no_name': 'Nta zina',
        'no_category': 'Nta cyiciro',
        'entered_amount': 'Umubare washyizwemo',
        'calculated_unit_cost': 'Igiciro ku kintu kimwe',
        'total_investment_value': 'Agaciro kose',
        'fill_all_required': 'Uzuza ibyangombwa byose kugira ngo ubike.',
        'fill_all_required_error': 'Uzuza neza imyanya yose isabwa',
        'ready_for_recording': 'Igicuruzwa cyiteguye kubikwa mu bubiko.',
        'recording': 'Birabikwa...',
        'record_product': 'Bika igicuruzwa',
        'product_added_success': 'Igicuruzwa cyongewemo neza',
        'product_add_failed': 'Kwineza igicuruzwa byanze',
        'product_updated_success': 'Igicuruzwa cyahinduwe',
        'available': 'Bihari',
        'quantity_to_sell': 'Ingano ugiye kugurisha',
        'selling_price_per_unit': 'Igiciro cyo kugurisha (ku kintu kimwe)',
        'return_deadline': 'Itariki ntarengwa yo kugarura (bidahatirwa)',
        'profit_loss_preview': 'Inyungu n\'igihombo',
        'profit_per_unit': 'Inyungu ku kintu kimwe',
        'total_revenue': 'Amafaranga yose yinjiye',
        'total_profit_loss': 'Inyungu/Igihombo cyose',
        'complete_sale': 'Rangiza igurisha',
        'confirm_sale_desc': 'Uracyashaka kwemeza iri gurisha?',
        'yes_confirm_sale': 'Yego, Emeza igurisha',
        'change_confirmation_status': 'Hindura imiterere yo kwemezwa',
        'confirm_product_question': 'Uracyashaka kwemeza iki gicuruzwa?',
        'unconfirm_product_question': 'Uracyashaka gukuraho ishimangira ry\'iki gicuruzwa?',
        'confirm_change': 'Emeza ihinduka',
        'close': 'Funga',
        'permanent_action_desc': 'Iki gikorwa ntigishobora gusubirwamo.',
        'expected_profit': 'Inyungu yitezwe',
        'sell': 'Gurisha',
        'update': 'Hindura',
        'delete': 'Siba',
        'deleting': 'Birasibwa...',
        'branch': 'Ishami',
        'unassigned': 'Nta shami',
        'no_branch_assigned': 'Nta shami Ryahawe',
        'product_name': 'Izina ry\'igicuruzwa',
        'category_label': 'Icyiciro',
        'all_categories': 'Ibyiciro Byose',
        'model_label': 'Ubwoko',
        'cost_price': 'Igiciro cyaguze',
        'selling_price': 'Igiciro cyo kugurisha',
        'quantity_label': 'Ingano',
        'total_value': 'Agaciro kose',
        'status_label': 'Imiterere',
        'actions': 'Ibikorwa',
        'confirm': 'Emeza',
        'confirmed': 'Byemejwe',
        'export': 'Kohereza',
        'weekly_stats': 'Imibare y\'icyumweru',
        'monthly_stats': 'Imibare y\'ukwezi',
        'yearly_stats': 'Imibare y\'umwaka',
        'cost_configuration': 'Igenamiterere ry\'igiciro',
        'cost_per_unit': 'Igiciro ku kintu kimwe',
        'total_bulk_cost': 'Igiciro cyose hamwe',
        'select_branch': 'Hitamo ishami',
        'select_branch_for': 'Hitamo ishami rya',
        'unit': 'Igipimo',
        'pieces': 'Igice / kimwe',
        'bag': 'Umifuka (Bag)',
        'crate': 'Ikirato (Crate)',
        'liter': 'Litiro',
        'kilograms': 'Kilogarama',
        'gram': 'Garamu',
        'milliliter': 'Mililitiro',
        'sack': 'Isaho (Sack)',
        'bottle': 'Icupa',
        'pack': 'Ipaki',
        'box': 'Agasanduku',
        'meter': 'Metero',
        'added_date': 'Itariki byashiriweho',
        'confirmation': 'Kwemezwa',
        'confirmed_only': 'Byemejwe gusa',
        'unconfirmed_only': 'Bitarayemezwa gusa',
        'min_value': 'Agaciro gake',
        'max_value': 'Agaciro kanini',
        'min_qty': 'Ingano nkeya',
        'max_qty': 'Ingano nini',
        'all': 'Byose',
        'pick_date': 'Hitamo itariki',
        'clear_date': 'Siba itariki',
        'optional': 'bidahatirwa',
        'enter_placeholder': 'Andika...',
        'invalid_sale': 'Kugurisha nabi',
        'sold_success_msg': 'Byagurishijwe neza',
        'deleted_success': 'Byasibwe',
        'status_updated': 'Imiterere yahinduwe',
        'back_online_syncing': 'Internet yagarutse – Birakoherezwa...',
        'offline_changes_sync_later': 'Nta internet - impinduka zizabikwa numara kubona internet',
        'failed_load_branches': 'Gusoma amashami byanze',
        'using_cached_data': 'Gukoresha amakuru abitswe',
        'all_branches': 'Amashami Yose',
        'products_in': 'Ibicuruzwa muri',
        'your_branch': 'Ishami ryawe',
        'unknown_branch': 'Ishami ritazwi',
        'no_branch': 'Nta shami',
        'no_products_found_filters': 'Nta bicuruzwa byabonetse bijyanye n\'ibyo washakishije.',
        'no_products_found': 'Nta bicuruzwa byabonetse.',
        'cannot_set_past_date': 'Ntiwashyiraho itariki yashize',
        'cannot_sell_unconfirmed': 'Nushobora kugurisha igicuruzwa kitaremezwa.',

        // Auth - UPDATED & IMPROVED MESSAGES (Kinyarwanda)
        'welcome_back_login': 'Murakaza neza',
        'enter_details_login': 'Injiza imyirondoro yawe kugirango winjire.',
        'forgot_password': 'Wibagiwe ijambo ry\'ibanga?',
        'sign_in_button': 'Injira',
        'or_divider': 'Cyangwa',
        'google_login': 'Google',
        'dont_have_account': "Nta konti ufite?",
        'sign_up_link': 'Iyandikishe',
        'create_account_title': 'Fungura konti',
        'business_details_step': 'Injiza ibiranga ubucuruzi kugirango utangire.',
        'personal_details_step': 'Uzuza amakuru yawe bwite.',
        'upload_logo': 'Shyiraho Logo',
        'next_step': 'Komeza',
        'back_button': 'Subira inyuma',
        'create_account_button': 'Fungura Konti',
        'already_have_account': 'Usanganywe konti?',
        'password_placeholder': 'Shyiramo ijambo ry\'ibanga',

        // NEW AUTH ERROR MESSAGES (Kinyarwanda)
        'wrong_password': 'Ijambo ry\'ibanga siryo.',
        'invalid_email': 'Shyiramo imeri yizewe.',
        'too_many_attempts': 'Wagerageje kenshi cyane. Subira ugerageze nyuma y\'igihe gito.',
        'network_error': 'Habaye ikibazo ry\'internet. Wongere ugenzure uhuza ryawe.',
        'other': 'Ikindi',
        'select': 'Hitamo',
        'business_name_min': 'Izina ry\'ubucuruzi rigomba kugira inyuguti nibura 2',
        'district_required': 'Andika akarere kanyu',
        'sector_required': 'Andika umurenge wanyu',
        'cell_required': 'Andika akagari kanyu',
        'village_required': 'Andika umudugudu wanyu',
        'first_name_min': 'Izina rya mbere rigomba kugira inyuguti nibura 2',
        'last_name_min': 'Izina rya kabiri rigomba kugira inyuguti nibura 2',
        'phone_required': 'Andika nimero ya terefoni yizewe',
        'account_created_success': 'Konti yafunguwe! Uri gukoresha uburyo bw\'ubuntu (igerageza). Rizarangira mu kwezi kumwe.',
        'image_size_error': 'Ifoto igomba kuba iri munsi ya 5MB',
        'business_name_exists': 'Iri zina ry\'ubucuruzi ryasanzwe ryakoreshejwe.',
        'email_exists': 'Iyi imeri yasanzwe yarakoreshejwe.',
        'phone_exists': 'Iyi nimero yasanzwe yarakoreshejwe.',
        'profile_image_upload_failed': 'Gushyiraho ifoto byanze.',
        'user_not_found_create': 'Konti ntiyabonetse. Ushobora gufungura konti nshya ku buntu (ukwezi kwa mbere ni ubwoko bw\'igerageza).',
        'user_inactive_wait_admin': 'Konti yawe iracyategereje kwemezwa. Tegereza umuyobozi w\'ubucuruzi bwawe akayemeze.',
        'business_inactive_wait_central': 'Ubucuruzi bwawe ntiburakora. Tegereza umuyobozi wa sisitemu akabwemere.',

        // Keep old keys for backward compatibility
        'invalid_credentials': 'Imeri cyangwa ijambo ry\'ibanga sibyo.',
        'business_inactive_error': 'Business yanyu ntirakora. Tegereza admin abayemere.',
        'user_inactive_error': 'Konti yanyu ntirakora. Tegereza admin wanyu abayemere.',

        // Reports
        'business_report_title': 'Raporo y\'Ubucuruzi',
        'business_report_desc': 'Incamake yuzuye y\'ububiko, ibyagurishijwe, Ibyagaruwe, n\'ibyahanaguwe',
        'export_report': 'Sohora Raporo',
        'export_excel': 'Sohora muri Excel',
        'export_pdf': 'Sohora muri PDF',
        'report_context': 'Imiterere ya Raporo',
        'gross_profit': 'Inyungu Mbumbe',
        'net_profit': 'Inyungu Nyakuri',
        'total_store_value': 'Agaciro k\'Ububiko',
        'no_data_available': 'Nta makuru ya raporo ahari.',
        'total_value_processed': 'Agaciro kose kakozwe',
        'no_branch_assigned_msg': 'Nta shami ryahawe.',
        'contact_admin_access': 'Vugana n\'umuyobozi wawe kugirango ubone uburenganzira.',
        'no_data_match': 'Nta makuru ahuye',
        'unit_cost_label': 'Igiciro ku kintu',
        'profit_label': 'Inyungu',
        'sold_deleted_date_label': 'Itariki Byagurishijwe/Byasibwe',

        // Inventory (Sold/Restored/Deleted)
        'sold_products_title': 'Ibicuruzwa Byagurishijwe',
        'sold_products_desc': 'Reba kandi ucunge ibicuruzwa byagurishijwe',
        'restored_products_title': 'Ibicuruzwa Byasubijwe',
        'restored_products': 'Ibicuruzwa Byasubijwe',
        'restored_products_desc': 'Reba kandi ugurishe ibicuruzwa byasubijwe',
        'deleted_products_title': 'Ibicuruzwa Byasibwe (Trash)',
        'deleted_products': 'Ibicuruzwa Byasibwe (Trash)',
        'deleted_products_desc': 'Reba kandi ucunge ibicuruzwa byasibwe',
        'daily_income': 'Ayinjiye Uyu munsi',
        'weekly_income': 'Ayinjiye mu Cyumweru',
        'monthly_income': 'Ayinjiye mu Kwezi',
        'yearly_income': 'Ayinjiye mu Mwaka',
        'weekly_restored_value': 'Agaciro k\'Ibyagaruwe (Cyumweru)',
        'monthly_restored_value': 'Agaciro k\'Ibyagaruwe (Kwezi)',
        'yearly_restored_value': 'Agaciro k\'Ibyagaruwe (Mwaka)',
        'restore_selected': 'Subiza Ibyahiswemo',
        'restore_product': 'Subiza Igicuruzwa',
        'permanent_delete': 'Siba Burundu',
        'delete_selected': 'Siba Ibyahiswemo',
        'sell_restored': 'Gurisha Icyasubijwe',
        'return_product': 'Garura Igicuruzwa',
        'sale_record_deleted': 'Inyandiko y\'igurisha yasibwe',
        'restored_successfully': 'Byasubijwe neza',
        'deleted_permanently': 'Byasibwe burundu',
        'reason_label': 'Impamvu',
        'delete_reason': 'Impamvu yo gusiba',
        'restore_reason': 'Impamvu yo gusubiza',
        'income': 'Ayinjiye',
        'value': 'Agaciro',
        'generated_profit': 'Inyungu',
        'received_amount': 'Amafaranga yose',
        'actual_unit_cost': 'Igiciro Nyakuri',
        'available_stock': 'Bihari mu byasubijwe',
        'quantity_to_restore': 'Ingano yo gusubiza',
        'restore_confirm_question': 'Subiza iki gicuruzwa mu bubiko?',
        'delete_confirm_question': 'Siba burundu iki gicuruzwa?',
        'bulk_restore_confirm': 'Subiza ibicuruzwa byahiswemo?',
        'bulk_delete_confirm': 'Siba ibicuruzwa byahiswemo?',
        'no_sold_products': 'Nta bicuruzwa byagurishijwe byabonetse.',
        'no_restored_products': 'Nta bicuruzwa byasubijwe byabonetse.',
        'no_deleted_products': 'Nta bicuruzwa byasibwe byabonetse.',
        'displaying_sales_for': 'Hagaragazwa ibyagurishijwe:',
        'showing_restored_products_for': 'Hagaragazwa Ibyagaruwe:',
        'showing_restored_for': 'Hagaragazwa Ibyagaruwe:',
        'restoring_from_sale': 'Gusubiza ibyagurishijwe',
        'quantity_restore': 'Ingano igaruwe',
        'restore_qty_placeholder': 'Andika ingano igaruwe',
        'restore_reason_placeholder': 'Andika impamvu yo gusubiza',
        'confirm_restore': 'Emeza igaruwe',
        'restored_products_in': 'Ibicuruzwa byasubijwe muri',
        'all_restored_products_admin': 'Ibicuruzwa byose byasubijwe mu mashami yose',
        'deleted_products_from': 'Ibicuruzwa byasibwe muri',
        'all_deleted_products_admin': 'Ibicuruzwa byose byasibwe mu mashami yose',
        'no_deleted_products_found': 'Nta bicuruzwa byasibwe byabonetse.',
        'deleted_product_details': 'Ibiranga Igicuruzwa Cyasibwe',
        'restore_confirm_msg': 'Urashaka kugarura',
        'restore_selected_products_q': 'Kugarura Ibicuruzwa Byahiswemo?',
        'restore_selected_confirm_msg': 'Urashaka kugarura ibicuruzwa byahiswemo?',
        'permanently_delete_product_q': 'Gusiba Igicuruzwa Burundu?',
        'permanent_delete_warning': 'Urashaka gusiba burundu',
        'no_sold_products_date': 'Nta bicuruzwa byagurishijwe kuri iyi tariki.',
        'sold_product_details': 'Ibiranga Igicuruzwa Cyagurishijwe',
        'restore_sold_product': 'Garura Igicuruzwa Cyagurishijwe',
        'no_restored_products_date': 'Nta bicuruzwa byasubijwe kuri iyi tariki.',
        'restored_product_details': 'Ibiranga Igicuruzwa Cyasubijwe',
        'cost_price_base': 'Igiciro Cyaguze (Fatizo)',
        'selling_price_base': 'Igiciro Cyagurishijwe (Fatizo)',
        'sell_restored_product': 'Gurisha Igicuruzwa Cyasubijwe',
        'available_restored_stock': 'Bihari mu bubiko bwasubijwe',
        'quantity_sell': 'Ingano yo kugurisha',
        'quantity_placeholder': 'Shyiramo ingano...',
        'selling_price_placeholder': 'Shyiramo igiciro...',

        // Admin (Employees/Branches)
        'manage_employees_title': 'Cunga Abakozi',
        'manage_employees': 'Cunga Abakozi',
        'manage_employees_desc': 'Fungura kandi ucunge konti z\'abakozi',
        'employees': 'Abakozi',
        'create_manage_staff': 'Fungura kandi ucunge abakozi b\'ubucuruzi bwawe.',
        'add_employee': 'Ongeramo Umukozi',
        'photo': 'Ifoto',
        'created_at': 'Byakozwe',
        'assign_branch': 'Ha Ishami',
        'assigning': 'Birakorwa...',
        'assign_branch_desc': 'Hitamo ishami uha uyu mukozi.',
        'create_employee_title': 'Fungura Umukozi Mushya',
        'create_new_employee': 'Fungura Umukozi Mushya',
        'create_employee': 'Fungura Umukozi',
        'creating': 'Birakorwa...',
        'update_employee_title': 'Hindura Umukozi',
        'update_employee': 'Hindura Umukozi',
        'employee_details_title': 'Imyirondoro y\'Umukozi',
        'employee_details': 'Imyirondoro y\'Umukozi',
        'delete_employee_q': 'Siba Umukozi?',
        'delete_employee_confirm': 'Siba Umukozi?',
        'delete_employee_warning': 'Uyu mukozi arasibwa burundu. Ibi ntibishobora gusubirwamo.',
        'delete_selected_employees_q': 'Siba Abakozi Bahiswemo?',
        'delete_multiple_employees_warning': 'Abakozi {count} barasibwa burundu.',
        'name': 'Izina',
        'required_fields_error': 'Uzuza imyanya yose isabwa',
        'employee_updated_success': 'Umukozi yahinduwe neza',
        'offline_warning': 'Nta internet - impinduka zizabikwa numara kubona internet',
        'default_password_msg': 'Ijambo ry\'ibanga ry\'ibanze ni',

        'manage_branches_title': 'Cunga Amashami',
        'manage_branches': 'Cunga Amashami',
        'manage_branches_desc': 'Fungura, hindura, cyangwa siba amashami',
        'branches': 'Amashami',
        'branches_desc': 'Reba kandi ucunge amashami yawe yose.',
        'add_branch': 'Ongeramo Ishami',
        'branch_name': 'Izina ry\'Ishami',
        'example_branch_name': 'urugero: Kigali Main',
        'example_district': 'urugero: Gasabo',
        'create_branch_title': 'Fungura Ishami Rishya',
        'create_new_branch': 'Fungura Ishami Rishya',
        'create_branch': 'Fungura Ishami',
        'create_branch_desc': 'Uzuza ibisabwa kuri iri shami rishya.',
        'update_branch_title': 'Hindura Ishami',
        'update_branch': 'Hindura Ishami',
        'update_branch_desc': 'Hindura amakuru y\'ishami.',
        'branch_details_title': 'Imyirondoro y\'Ishami',
        'branch_details': 'Imyirondoro y\'Ishami',
        'delete_branch_q': 'Siba Ishami?',
        'delete_branch_confirm': 'Siba Ishami?',
        'delete_branch_warning': 'Iri shami rirasibwa burundu. Ibi ntibishobora gusubirwamo.',
        'delete_selected_branches_q': 'Siba Amashami Ahiswemo?',
        'delete_multiple_branches_warning': 'Amashami {count} arasibwa burundu.',
        'offline_mode': 'Nta internet - impinduka zizabikwa numara kubona internet',
        'default_password_notice': 'Ijambo ry\'ibanga ribanza rizaba',
        'fill_all_fields_error': 'Uzuza imyanya yose',
        'branch_created_success': 'Ishami ryafunguwe neza',
        'branch_updated_success': 'Ishami ryahinduwe neza',
        'branch_removed_success': 'Ishami ryasibwe neza',
        'employee_created': 'Umukozi yafunguwe neza',
        'employee_updated': 'Umukozi yahinduwe neza',
        'employee_deleted': 'Umukozi yasibwe neza',
        'no_employees_found': 'Nta bakozi babonetse.',
        'search_employees': 'Shakisha abakozi...',
        'no_branches_found': 'Nta mashami abonetse.',
        'search_branches': 'Shakisha amashami...',

        // Shared
        'loading': 'Biratunganywa...',
        'error': 'Ikosa',
        'success': 'Byagenze neza',
        'yes': 'Yego',
        'no': 'Oya',
        'account_deactivated': 'Konti yawe yahagaritswe. Vugana n\'ushinzwe sisitemu.',
        'business_inactive': 'Konti y\'ubucuruzi bwawe ntigikora. Vugana n\'ushinzwe sisitemu.',
        'switch_theme': 'Hindura Aho Kureba (Theme)',
        'light_mode': 'Urumuri',
        'dark_mode': 'Umwijima',
        'language': 'Ururimi',
        'theme': 'uko igaragara',
        'english': 'Icyongereza',
        'kinyarwanda': 'Ikinyarwanda',
        'access_denied': 'Ntimwemerewe kwinjira',
        'checking_details': 'Biragenzurwa...',
        'sold_products': 'Ibyagurishijwe',
        'sold_products_from': 'Ibicuruzwa byagurishijwe muri',
        'all_sold_products_admin': 'Ibicuruzwa byagurishijwe mu mashami yose',
        'income_label': 'Amafaranga yinjiye uyu munsi',
        'total_received': 'Amafaranga yakiriwe',
        'profit_loss': 'Inyungu/Igihombo',
        'sold_date': 'Itariki byagurishirijweho',
        'sold_qty': 'Ingano yagurishijwe',
        'search_sold_products': 'Shakisha ibyagurishijwe...',
        'search_restored_products': 'Shakisha Ibyagaruwe...',
        'total_cost_value': "Agaciro k'ishoramari",
        'restored_date': 'Itariki byagaruwe',
        'restored_qty': 'Ingano yasubijwe',
        'search_deleted_products': 'Shakisha ibyasibiwe mu mase...',
        'deleted_date': 'Itariki byasibiweho',
        'delete_permanently': 'Siba Burundu',
        'restore_product_q': 'Kugarura Igicuruzwa?',
        'restoring': 'Biragarurwa...',
        'expiry_date': 'Itariki yo kurenza igihe',
        'days_remaining': 'Iminsi isigaye',
        'expired_product': 'Igicuruzwa cyarengeje igihe',
        'expired_products': 'Ibicuruzwa byarengeje igihe',
        'never_expires': 'Nta gihe cyo kurangira igira',
        'expires_soon': 'Kirenda  kurenza igihe',
        'days_left': 'iminsi',

        // Landing Page - Navigation
        'nav_features': 'Ibiranga',
        'nav_services': 'Serivisi',
        'nav_pricing': 'Ibiciro',
        'nav_testimonials': 'Ubuhamya',
        'nav_partners': 'Abafatanyabikorwa',
        'nav_login': 'Injira',
        'nav_get_started': 'Tangira',

        // Landing Page - Hero
        'hero_title_1': 'Urubuga rwiza rwo gucunga ububiko bw\'',
        'hero_title_highlight': 'ubucuruzi butera imbere',
        'hero_subtitle': "Teza imbere ububiko bwawe ukoresheje SmartStock igenzura neza, igahuriza hamwe amashami menshi, igatanga raporo, n'isesengura rifatika.",
        'hero_cta_primary': 'Tangira ku buntu',
        'hero_cta_secondary': 'Vugana natwe',
        'hero_feature_1': 'Genura ububiko mu minota',
        'hero_feature_2': 'Kurinda amakuru',
        'hero_feature_3': 'Cunga ikipe yawe',
        'hero_rating': 'INYENYERI 5',
        'hero_no_card': 'nta karita ya banki ikenewe',
        'hero_daily_sales': 'Igurisha ryu munsi',

        // Landing Page - Stats
        'stat_happy_clients': 'Abakiriya bishimye',
        'stat_business_accounts': 'Konti z\'ubucuruzi',
        'stat_trusted_customers': 'Abakiriya bizewe',
        'stat_success_rate': 'Igipimo cy\'intsinzi',

        // Landing Page - Features
        'features_title': 'Ibiranga Bizamura Ubucuruzi Bwawe',
        'features_subtitle': 'Ibintu byose ukeneye kugira ngo ucunge ububiko neza uteze imbere ubucuruzi bwawe.',
        'feature_inventory_title': 'Imicungire y\'Ububiko',
        'feature_inventory_desc': 'Kurikirana ububiko, genzura ingano y\'ibicuruzwa, kandi umenye uko ibintu bimeze ako kanya.',
        'feature_branch_title': 'Imicungire y\'Amashami n\'Abakozi',
        'feature_branch_desc': 'Cunga abakozi, utange inshingano, kandi ugenzure uko amashami menshi akora.',
        'feature_reports_title': 'Raporo Zikora Zonyine',
        'feature_reports_desc': 'Bona raporo zirambuye ku kugurisha, inyungu, n\'imiterere y\'ububiko mu buryo bwikora.',
        'feature_alerts_title': 'Kumenyeshwa ako kanya',
        'feature_alerts_desc': 'Akira ubutumwa ako kanya igihe ibicuruzwa bigabanutse cyangwa hari igikorwa gikenewe.',
        'feature_security_title': 'Umutekano wo ku rwego rwo hejuru',
        'feature_security_desc': 'Umutekano wo ku rwego rwa banki kugira ngo amakuru y\'ubucuruzi bwawe abeatekanye.',
        'feature_backup_title': 'Ububiko bwo kuri Interineti',
        'feature_backup_desc': 'Kubika amakuru mu buryo bwikora (Cloud Backup) bituma amakuru yawe ahoraatekanye.',

        // Landing Page - Services
        'services_title': 'Serivisi Zisumbuyeho',
        'services_subtitle': 'Byakorewe ubucuruzi bugezweho bushaka gutera imbere no kwizerwa.',
        'service_tracking_title': 'Gukurikirana Ibicuruzwa',
        'service_tracking_desc': 'Kurikirana buri gicuruzwa n\'amateka yacyo yose.',
        'service_multi_branch_title': 'Gushyigikira Amashami Menshi',
        'service_multi_branch_desc': 'Cunga amashami atagira ingano n\'aho aherereye ukoresheje urubuga rumwe.',
        'service_analytics_title': 'Isesengura Ryimbitse',
        'service_analytics_desc': 'Bona ibisubizo bifatika ukoresheje isesengura ryifashisha ikoranabuhanga.',
        'service_collaboration_title': 'Gukorera hamwe nk\'Ikipe',
        'service_collaboration_desc': 'Fasha ikipe yawe gukorera hamwe buri wese afite inshingano ze.',

        // Landing Page - Testimonials
        'testimonials_label': 'Ubuhamya',
        'testimonials_title': 'Byizerwa n\'abayobozi',
        'testimonials_subtitle': 'bo mu nzego zitandukanye',
        'testimonials_desc': 'Menya impamvu abanyamwuga bizera ibisubizo byacu kugira ngo basohoze intego zabo.',
        'testimonials_cta': 'Soma Inkuru z\'Intsinzi',

        // Landing Page - Pricing
        'pricing_title': 'Ibiciro Byoroheje kandi Bisobanutse',
        'pricing_subtitle': 'Hitamo gahunda ibereye ubucuruzi bwawe. Tangira ku buntu, hindura igihe cyose.',
        'pricing_best_value': 'Agaciro keza',
        'pricing_pay_now': 'Ishyura Nonaha',
        'pricing_duration_month': '/kwezi',
        'pricing_duration_year': '/mwaka',
        'pricing_duration_forever': '/burundu',

        // Plans
        'plan_free_name': 'Gahunda y\'Igerageza (Ubuntu)',
        'plan_free_desc': '(Ukwezi kwa Mbere Gusa)',
        'plan_monthly_name': 'Gahunda ya Buri Kwezi',
        'plan_monthly_desc': '(Kubucuruzi Bukora)',
        'plan_annually_name': 'Gahunda ya Buri Mwaka',
        'plan_annually_desc': '(Zigama 25%)',
        'plan_forever_name': 'Gahunda ya Burundu',
        'plan_forever_desc': 'Konti ya Burundu – Wishyura Rimwe',

        // Plan Features
        'feature_all_unlocked': 'Ibya SmartStock byose birafunguye',
        'feature_unlimited_products': 'Ibicuruzwa & Kugurisha Bitagira Umupaka',
        'feature_unlimited_employees': 'Abakozi & Amashami Bitagira Umupaka',
        'feature_multi_branch': 'Gucunga Amashami Menshi',
        'feature_advanced_reports': 'Raporo & Isesengura rirambuye',
        'feature_returns': 'Kugarura & Kugarura Ibyasibwe',
        'feature_monitoring': 'Gukurikirana Ibyakozwe (Admin)',
        'feature_support': 'Kuvugurura Sisitemu & Ubufasha',

        // Landing Page - CTA Bottom
        'cta_title': 'Witeguye Guteza Imbere Ubucuruzi Bwawe?',
        'cta_subtitle': 'Iyungure n\'ibindi bigo amagana bimaze gukoresha SmartStock mu koroshya imicungire y\'ububiko bwabyo.',
        'cta_start_free': 'Tangira Igerageza ry\'Ubuntu',
        'cta_learn_more': 'Menya ibindi',

        // Landing Page - Partners
        'partners_title_1': 'Teza imbere ubucuruzi nka',
        'partners_title_highlight': 'SmartStock',
        'partners_title_2': 'umufatanyabikorwa',
        'partners_desc': "Dufatanye. Iyungure n\'umuryango w\'abafatanyabikorwa bacu kugira ngo duhe serivisi nziza abakiriya bacu kandi duteze imbere ubucuruzi.",
        'partners_apply': 'Saba ubu',

        // Landing Page - Footer
        'footer_desc': 'Umufatanyabikorwa wawe wizewe mu micungire y\'ububiko ku bucuruzi.',
        'footer_product': 'Igicuruzwa',
        'footer_company': 'Ikigo',
        'footer_stay_updated': 'Menya Amakuru',
        'footer_whatsapp_desc': 'Injira muri channel yacu ya WhatsApp kugira ngo umenye amakuru agezweho.',
        'footer_join_whatsapp': 'Injira muri WhatsApp Channel',
        'footer_about': 'Turi bande',
        'footer_contact': 'Twandikire',
        'footer_support': 'Ubufasha',
        'footer_rights': '© 2025 SmartStock. Uburenganzira bwose buhubijwe. Yakozwe na SmartStock Developer Team.',
        'footer_dev_team': 'Injira mu Ikipe y\'Abadeveloper bacu ube umwe natwe.',
        'footer_dev_link': 'Ikipe y\'Abadeveloper',
        'fab_help': 'Ukeneye ubufasha? Vugana natwe!',
        'add_expiry_date': 'Shyiraho itariki yo kurenza igihe (Bihiswemo)',
        'subscription_expired_title': 'Ifatabuguzi Ryarangiye',
        'subscription_expired_message': 'Ifatabuguzi ryawe ryarangiye. Ugomba kwishyura irindi fatabuguzi kugira ngo ukomeze gukoresha urubuga.',
        'subscription_expired_link': 'Jya ahabanza kugira ngo wishyure',

        // Payment Dialog
        'plan': 'Gahunda',
        'locale': 'rw-RW',
        'select_payment_method': 'Hitamo uburyo bwo kwishyura',
        'pay_amount_for': 'Ishyura',
        'plan_standard': 'Gahunda Iciriritse',
        'plan_enterprise': 'Gahunda Yisumbuyeho',
        'plan_free': "Gahunda y'Ubuntu",
        'for_plan': 'kuri gahunda ya',
        'mtn_momo': 'MTN Mobile Money',
        'airtel_money': 'Airtel Money',
        'bank_transfer_bk': 'Kwishyura kuri Banki (BK)',
        'finding_account': 'Gushaka konti...',
        'continue': 'Komeza',
        'verify_account_details': 'Genzura neza amakuru ya konti',
        'verify_account_desc': 'Uzuza amakuru ya konti yawe kugira ngo tumenye ubucuruzi wishyurira.',
        'password': 'Ijambo ry\'ibanga',
        'back': 'Subira inyuma',
        'verifying': 'Kugenzura...',
        'verify_next': 'Genzura & Komeza',
        'or': 'Cyangwa',
        'continue_with_google': 'Komeza na Google',
        'complete_payment': 'Shyira iherezo ku bwisungane',
        'account_status': 'Imiterere ya Konti',
        'account_active_msg': 'Konti yawe irakora ubu.',
        'send_money_desc': 'Ohereza amafaranga ku makuru ari hano hasi.',
        'subscription_ends_on': 'Ifatabuguzi rirangira ku itariki',
        'days_remaining_lower': 'iminsi isigaye',
        'continue_to_dashboard': 'Komeza kuri Dashboard',
        'phone_number': 'Nimero ya terefoni',
        'account_number': 'Nimero ya konti',
        'recipient': 'Uyahawe',
        'your_phone_placeholder': 'Andika nimero yawe ya terefoni',
        'your_account_placeholder': 'Andika nimero yawe ya konti',
        'your_name_label': 'Izina ryawe',
        'your_name_placeholder': 'Andika amazina yawe yose',
        'processing': 'Birimo gukorwa...',
        'confirm_payment': 'Emeza ubwishyu',
        'need_help_whatsapp': 'Ukeneye ubufasha? Twandikire kuri WhatsApp',
        'payment_submitted': 'Ubwishyu bwakiriwe!',
        'payment_received_msg': 'Twakiriye ubusabe bwawe bwo kwishyura.',
        'waiting_for_approval': 'Bitegereje kwemezwa',
        'admin_verification_msg': 'Ifatabuguzi ryawe riraba rifunguye mu gihe umuyobozi amaze kwemeza ubwishyu bwawe. Ibi bikunze gufata iminota 15 kugeza kuri 30.',
        'close_wait': 'Funga & Tegereza',

        // Toasts
        'copied_to_clipboard': 'Byanakunzwe',
        'user_record_not_found': 'Konti ntiyabonetse',
        'no_business_linked': 'Nta bucuruzi bufitanye isano n\'iyi konti',
        'business_details_not_found': 'Amakuru y\'ubucuruzi ntiyabonetse',
        'failed_fetch_business': 'Ntibyakunze kubona amakuru y\'ubucuruzi',
        'enter_email_password': 'Andika imeri n\'ijambo ry\'ibanga',
        'account_verified': 'Konti yemejwe!',
        'invalid_email_password': 'Imeri cyangwa ijambo ry\'ibanga si byo',
        'verification_failed': 'Ntibyakunze kwemezwa',
        'google_verification_failed': 'Ntibyakunze kwemezwa na Google',
        'session_expired_verify': 'Igihe cyarangiye. Mwongere mwemeze konti.',
        'payment_failed_try_again': 'Ntibyakunze kwishyura. Mwongere mugezeho.',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguageState(prev => {
            const newLang = prev === 'en' ? 'rw' : 'en';
            localStorage.setItem('language', newLang);
            return newLang;
        });
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};