
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'rw';

interface Translations {
    [key: string]: {
        [key: string]: string;
    };
}

const translations: Translations = {
    en: {
        // Header
        'blockchain': 'Blockchain',
        'account': 'Account',
        'logout': 'Logout',
        'switch_language': 'Switch Language',
        'search_placeholder': 'Search anything...',

        // Navigation
        'dashboard_label': 'Dashboard',
        'store_label': 'Products Store',
        'sold_label': 'Products Sold',
        'restored_label': 'Products Restored',
        'trash_label': 'Trash',
        'branches_label': 'Manage Branch',
        'employees_label': 'Manage Employees',
        'reports_label': 'Reports',
        'welcome_back': 'Welcome back,',
        'need_help': 'Need help? Contact support 24/7.',
        'sign_out': 'Sign Out',

        // Dashboard
        'dashboard_title': 'Dashboard',
        'inventory_console': 'Inventory Console',
        'real_time_analytics': 'Real-time Stock Value & Profit Analytics',
        'system_status': 'System Status',
        'live_connection': 'Live Connection',
        'dashboard_context': 'Dashboard context:',
        'weekly_stock_value': 'Weekly Stock Value',
        'monthly_stock_value': 'Monthly Stock Value',
        'yearly_stock_value': 'Yearly Stock Value',
        'total_net_profit': 'Total Net Profit',
        'net_profit_subtitle': 'Profit from all sold products after calculated loss',
        'current_stock_value': 'Current Stock Value',
        'total_stock_value_subtitle': 'Total value of all products in stock',
        'total_loss': 'Total Loss',
        'total_loss_subtitle': 'Total loss from all sold products',
        'weekly_activity': 'Weekly Activity',
        'monthly_activity': 'Monthly Activity',
        'yearly_activity': 'Yearly Activity',
        'stock_highlights': 'Stock Highlights',
        'most_stocked': 'MOST STOCKED PRODUCT',
        'least_stocked': 'LEAST STOCKED PRODUCT',
        'never_updated': 'Never Updated',
        'in_stock': 'In Stock',
        'pending_actions': 'Pending Actions',
        'sold': 'Sold',
        'restored': 'Restored',
        'deleted': 'Deleted',
        'low_stock': 'Low Stock',
        'out_of_stock': 'Out of Stock',
        'avg_stock': 'Avg Stock',
        'total_products': 'Total Products',
        'categories': 'Categories',
        'models': 'Models',
        'all_products': 'All products',
        'unique_categories': 'Unique categories',
        'unique_models': 'Unique models',
        'added_today': 'Added Today',
        'added_this_week': 'Added This Week',
        'added_this_month': 'Added This Month',
        'updated_today': 'Updated Today',
        'new_today': 'New today',
        'this_week': 'This week',
        'this_month': 'This month',
        'updated_at': 'Updated today',
        'today': 'Today',

        // Profile
        'profile_title': 'My Profile',
        'edit_profile': 'Edit Profile',
        'save': 'Save',
        'cancel': 'Cancel',
        'personal_details': 'Personal Details',
        'business_info': 'Business Information',
        'address_settings': 'Address Settings',
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'gender': 'Gender',
        'phone': 'Phone',
        'district': 'District',
        'sector': 'Sector',
        'cell': 'Cell',
        'village': 'Village',
        'active': 'Active',
        'pending': 'Pending',
        'role': 'Role',
        'intro': 'Intro',
        'admin_account': 'Administrator Account',
        'staff_account': 'Staff Member',
        'works_at': 'Works at',
        'lives_in': 'Lives in',
        'no_phone': 'No phone',
        'edit_details': 'Edit Details',
        'not_set': 'Not set',
        'business_name': 'Business Name',
        'settings': 'Settings',
        'email_address': 'Email Address',
        'update_email_desc': 'Update your email address',
        'password_label': 'Password',
        'change_password_desc': 'Change your security password',
        'pending_changes': 'pending changes',
        'verify_identity': 'Verify Your Identity',
        'create_new_password': 'Create New Password',
        'current_password': 'Current Password',
        'enter_current_password': 'Enter your current password',
        'new_password': 'New Password',
        'enter_new_password': 'Enter new password',
        'confirm_password': 'Confirm New Password',
        'confirm_new_password_placeholder': 'Confirm your new password',
        'passwords_dont_match': 'Passwords do not match.',
        'password_min_length': 'Password must be at least 6 characters.',
        'continue_button': 'Continue',
        'update_password': 'Update Password',
        'update_email': 'Update Email',
        'reset_password': 'Reset Password',
        'delete_account': 'Delete Account',
        'delete_confirm_desc': 'This action is permanent and cannot be undone. All your data will be deleted.',
        'delete_my_account': 'Delete My Account',

        // Store / Products
        'products_store': 'Products Store',
        'all_products_in_stock': 'All products currently in stock',
        'search_products': 'Search products...',
        'add_product': 'Add Product',
        'add_new_product': 'Add New Product',
        'edit_product_title': 'Edit Product',
        'update_product': 'Update Product',
        'update_product_desc': 'Update product details and see changes in real-time',
        'product_details': 'Product Details',
        'sell_product': 'Sell Product',
        'confirm_sale': 'Confirm Sale',
        'delete_product_confirm': 'Delete Product?',
        'requires_admin_confirm': 'Requires admin confirmation',
        'auto_confirmed': 'Auto-confirmed',
        'live_preview': 'Live Preview',
        'product_identity': 'Product Identity',
        'no_name': 'No Name',
        'no_category': 'No Category',
        'entered_amount': 'Entered Amount',
        'calculated_unit_cost': 'Calculated Unit Cost',
        'total_investment_value': 'Total Investment Value',
        'fill_all_required': 'Please fill all required fields to record.',
        'ready_for_recording': 'Product ready for recording to inventory.',
        'recording': 'Recording...',
        'record_product': 'Record Product',
        'available': 'Available',
        'quantity_to_sell': 'Quantity to Sell',
        'selling_price_per_unit': 'Selling Price (per unit)',
        'return_deadline': 'Return Deadline (optional)',
        'profit_loss_preview': 'Profit & Loss Preview',
        'profit_per_unit': 'Profit per Unit',
        'total_revenue': 'Total Revenue',
        'total_profit_loss': 'Total Profit/Loss',
        'complete_sale': 'Complete Sale',
        'confirm_sale_desc': 'Are you sure you want to confirm this sale?',
        'yes_confirm_sale': 'Yes, Confirm Sale',
        'change_confirmation_status': 'Change Confirmation Status',
        'confirm_product_question': 'Are you sure you want to confirm this product?',
        'unconfirm_product_question': 'Are you sure you want to unconfirm this product?',
        'confirm_change': 'Confirm Change',
        'close': 'Close',
        'permanent_action_desc': 'This action cannot be undone.',
        'expected_profit': 'Expected Profit',
        'sell': 'Sell',
        'update': 'Update',
        'delete': 'Delete',
        'branch': 'Branch',
        'product_name': 'Product Name',
        'category_label': 'Category',
        'model_label': 'Model',
        'cost_price': 'Cost Price',
        'selling_price': 'Selling Price',
        'quantity_label': 'Quantity',
        'total_value': 'Total Value',
        'status_label': 'Status',
        'actions': 'Actions',
        'confirm': 'Confirm',
        'confirmed': 'Confirmed',
        'export': 'Export',
        'weekly_stats': 'Weekly Stats',
        'monthly_stats': 'Monthly Stats',
        'yearly_stats': 'Yearly Stats',
        'cost_configuration': 'Cost Configuration',
        'cost_per_unit': 'Cost Per Unit',
        'total_bulk_cost': 'Total Bulk Cost',
        'select_branch': 'Select Branch',
        'unit': 'Unit',
        'pieces': 'Pieces (pcs)',
        'bag': 'Bag',
        'crate': 'Crate',
        'liter': 'Liter',
        'kilograms': 'Kilograms (kg)',
        'sack': 'Sack',
        'bottle': 'Bottle',
        'pack': 'Pack',
        'added_date': 'Added Date',
        'confirmation': 'Confirmation',
        'confirmed_only': 'Confirmed Only',
        'unconfirmed_only': 'Unconfirmed Only',
        'min_value': 'Min Value',
        'max_value': 'Max Value',
        'min_qty': 'Min Qty',
        'max_qty': 'Max Qty',
        'all': 'All',
        'pick_date': 'Pick a date',
        'clear_date': 'Clear Date',
        'optional': 'optional',

        // Shared
        'loading': 'Loading...',
        'error': 'Error',
        'success': 'Success',
        'yes': 'Yes',
        'no': 'No',
    },
    rw: {
        // Header
        'blockchain': 'Blockchain',
        'account': 'Konti yanjye',
        'logout': 'Sohoka',
        'switch_language': 'Hindura Ururimi',
        'search_placeholder': 'Shakisha ikintu cyose...',

        // Navigation
        'dashboard_label': 'Incamake',
        'store_label': 'Ububiko',
        'sold_label': 'Byagurishijwe',
        'restored_label': 'Byasubijwe',
        'trash_label': 'Trash',
        'branches_label': 'Amashami',
        'employees_label': 'Abakozi',
        'reports_label': 'Raporo',
        'welcome_back': 'Muraho neza,',
        'need_help': 'Ukeneye ubufasha? Twandikire igihe cyose.',
        'sign_out': 'Sohoka',

        // Dashboard
        'dashboard_title': 'Incamake',
        'inventory_console': 'Imicungire y\'ububiko',
        'real_time_analytics': 'Isesengura ry\'agaciro k\'ibicuruzwa n\'inyungu',
        'system_status': 'Imiterere ya sisitemu',
        'live_connection': 'Ihuza rirahari',
        'dashboard_context': 'Imiterere y\'incamake:',
        'weekly_stock_value': 'Agaciro k\'ibicuruzwa ku cyumweru',
        'monthly_stock_value': 'Agaciro k\'ibicuruzwa ku kwezi',
        'yearly_stock_value': 'Agaciro k\'ibicuruzwa ku mwaka',
        'total_net_profit': 'Inyungu Neti',
        'net_profit_subtitle': 'Inyungu ivuye mu bicuruzwa byagurishijwe nyuma yo gukuramo igombo',
        'current_stock_value': 'Agaciro k\'ibicuruzwa bihari',
        'total_stock_value_subtitle': 'Agaciro kose k\'ibicuruzwa biri mu bubiko',
        'total_loss': 'Igihombo cyose',
        'total_loss_subtitle': 'Igihombo cyose cyavuye mu bicuruzwa byagurishijwe',
        'weekly_activity': 'Ibikorwa by\'icyumweru',
        'monthly_activity': 'Ibikorwa by\'ukwezi',
        'yearly_activity': 'Ibikorwa by\'umwaka',
        'stock_highlights': 'Ibyingenzi mu bubiko',
        'most_stocked': 'IGICURUZWA CYINSHI',
        'least_stocked': 'IGICURUZWA GIKE',
        'never_updated': 'Bitigeze bihindurwa',
        'in_stock': 'Bihari',
        'pending_actions': 'Ibitegerejwe',
        'sold': 'Byagurishijwe',
        'restored': 'Byasubijwe',
        'deleted': 'Byahanaguwe',
        'low_stock': 'Ibike cyane',
        'out_of_stock': 'Byashize',
        'avg_stock': 'Impuzandengo',
        'total_products': 'Ibicuruzwa byose',
        'categories': 'Ibyiciro',
        'models': 'Ubwoko',
        'all_products': 'Ibicuruzwa byose',
        'unique_categories': 'Ibyiciro byihariye',
        'unique_models': 'Ubwoko bwihariye',
        'added_today': 'Byashelwe uyu munsi',
        'added_this_week': 'Byashelwe iki cyumweru',
        'added_this_month': 'Byashelwe uku kwezi',
        'updated_today': 'Byahinduwe uyu munsi',
        'new_today': 'Bishya uyu munsi',
        'this_week': 'Iki cyumweru',
        'this_month': 'Uku kwezi',
        'updated_at': 'Byahinduwe uyu munsi',
        'today': 'Uyu munsi',

        // Profile
        'profile_title': 'Umwirondoro wanjye',
        'edit_profile': 'Hindura Umwirondoro',
        'save': 'Bika',
        'cancel': 'Reka',
        'personal_details': 'Ibiranga umuntu',
        'business_info': 'Ibiranga ubucuruzi',
        'address_settings': 'Ibiranga aho uba',
        'first_name': 'Izina rya mbere',
        'last_name': 'Izina rya kabiri',
        'gender': 'Igitsina',
        'phone': 'Terefone',
        'district': 'Akarere',
        'sector': 'Umurenge',
        'cell': 'Akagari',
        'village': 'Umudugudu',
        'active': 'Birakora',
        'pending': 'Birategerejwe',
        'role': 'Inshingano',
        'intro': 'Iriburiro',
        'admin_account': 'Konti y\'uyiyobora',
        'staff_account': 'Umukozi',
        'works_at': 'Akora muri',
        'lives_in': 'Atuye mu',
        'no_phone': 'Nta terefone ihari',
        'edit_details': 'Hindura ibiranga umuntu',
        'not_set': 'Ntabwo rwashyizwemo',
        'business_name': 'Izina ry\'ubucuruzi',
        'settings': 'Igenamiterere',
        'email_address': 'Imeri',
        'update_email_desc': 'Hindura imeri yawe',
        'password_label': 'Ijambo ry\'ibanga',
        'change_password_desc': 'Hindura ijambo ry\'ibanga ryawe',
        'pending_changes': 'ibyahinduwe bitarabikwa',
        'verify_identity': 'Erekana ko ari wowe',
        'create_new_password': 'Shiraho ijambo ry\'ibanga rishya',
        'current_password': 'Ijambo ry\'ibanga rya none',
        'enter_current_password': 'Shyiramo ijambo ry\'ibanga rya none',
        'new_password': 'Ijambo ry\'ibanga rishya',
        'enter_new_password': 'Shyiramo ijambo ry\'ibanga rishya',
        'confirm_password': 'Emeza ijambo ry\'ibanga rishya',
        'confirm_new_password_placeholder': 'Subiramo ijambo ry\'ibanga rishya',
        'passwords_dont_match': 'Amagambo y\'ibanga ntabwo ahuye.',
        'password_min_length': 'Ijambo ry\'ibanga rigomba kugira imigombane nibura 6.',
        'continue_button': 'Komeza',
        'update_password': 'Hindura ijambo ry\'ibanga',
        'update_email': 'Hindura Imeri',
        'reset_password': 'Siba ijambo ry\'ibanga',
        'delete_account': 'Siba konti',
        'delete_confirm_desc': 'Ibi bikorwa ntibishobora gusubirwamo. Amakuru yawe yose azasibwa.',
        'delete_my_account': 'Siba konti yanjye',

        // Store / Products
        'products_store': 'Ububiko',
        'all_products_in_stock': 'Ibicuruzwa byose biri mu bubiko',
        'search_products': 'Shakisha ibicuruzwa...',
        'add_product': 'Ongeramo igicuruzwa',
        'add_new_product': 'Ongeramo igicuruzwa gishya',
        'edit_product_title': 'Hindura igicuruzwa',
        'update_product': 'Husubira guhindura igicuruzwa',
        'update_product_desc': 'Hindura ibiranga igicuruzwa unarebe uko bihinduka ako kanya',
        'product_details': 'Ibiranga igicuruzwa',
        'sell_product': 'Gurisha igicuruzwa',
        'confirm_sale': 'Emeza igurisha',
        'delete_product_confirm': 'Siba igicuruzwa?',
        'requires_admin_confirm': 'Bisaba kwemezwa n\'umuyobozi',
        'auto_confirmed': 'Byemejwe ako kanya',
        'live_preview': 'Reba uko bimeze',
        'product_identity': 'Umwirondoro w\'igicuruzwa',
        'no_name': 'Nta zina',
        'no_category': 'Nta cyiciro',
        'entered_amount': 'Umubare washyizwemo',
        'calculated_unit_cost': 'Igiciro ku kintu kimwe',
        'total_investment_value': 'Agaciro kose kashowe',
        'fill_all_required': 'Tuzuza ibyangombwa byose kugira ngo ubike.',
        'ready_for_recording': 'Igicuruzwa cyiteguye kubikwa mu bubiko.',
        'recording': 'Birabikwa...',
        'record_product': 'Bika igicuruzwa',
        'available': 'Bihari',
        'quantity_to_sell': 'Ingano ugiye kugurisha',
        'selling_price_per_unit': 'Igiciro cyo kugurisha (ku kintu kimwe)',
        'return_deadline': 'Itariki ntarengwa yo kugarura (bidahatirwa)',
        'profit_loss_preview': 'Inyungu n\'igihombo',
        'profit_per_unit': 'Inyungu ku kintu kimwe',
        'total_revenue': 'Amafaranga yose yinjiye',
        'total_profit_loss': 'Inyungu/Igihombo cyose',
        'complete_sale': 'Rangiza igurisha',
        'confirm_sale_desc': 'Uracyashaka kwemeza iri gurisha?',
        'yes_confirm_sale': 'Yego, Emeza igurisha',
        'change_confirmation_status': 'Hindura imiterere yo kwemezwa',
        'confirm_product_question': 'Uracyashaka kwemeza iki gicuruzwa?',
        'unconfirm_product_question': 'Uracyashaka gukuraho ishimangira ry\'iki gicuruzwa?',
        'confirm_change': 'Emeza ihinduka',
        'close': 'Funga',
        'permanent_action_desc': 'Iki gikorwa ntigishobora gusubirwamo.',
        'expected_profit': 'Inyungu yitezwe',
        'sell': 'Gurisha',
        'update': 'Hindura',
        'delete': 'Siba',
        'branch': 'Ishami',
        'product_name': 'Izina ry\'igicuruzwa',
        'category_label': 'Icyiciro',
        'model_label': 'Ubwoko',
        'cost_price': 'Igiciro cyaguze',
        'selling_price': 'Igiciro cyo kugurisha',
        'quantity_label': 'Ingano',
        'total_value': 'Agaciro kose',
        'status_label': 'Imiterere',
        'actions': 'Ibikorwa',
        'confirm': 'Emeza',
        'confirmed': 'Byemejwe',
        'export': 'Kohereza',
        'weekly_stats': 'Imibare y\'icyumweru',
        'monthly_stats': 'Imibare y\'ukwezi',
        'yearly_stats': 'Imibare y\'umwaka',
        'cost_configuration': 'Igenamiterere ry\'igiciro',
        'cost_per_unit': 'Igiciro ku kintu kimwe',
        'total_bulk_cost': 'Igiciro cyose hamwe',
        'select_branch': 'Hitamo ishami',
        'unit': 'Igipimo',
        'pieces': 'Ibisanzwe (pcs)',
        'bag': 'Umfuka (Bag)',
        'crate': 'Ikarato (Crate)',
        'liter': 'Litiro (Liter)',
        'kilograms': 'Ibiro (kg)',
        'sack': 'Isaho (Sack)',
        'bottle': 'Icupa (Bottle)',
        'pack': 'Paki (Pack)',
        'added_date': 'Itariki byashiriweho',
        'confirmation': 'Kwemezwa',
        'confirmed_only': 'Byemejwe gusa',
        'unconfirmed_only': 'Bitarayemezwa gusa',
        'min_value': 'Agaciro gake',
        'max_value': 'Agaciro kanini',
        'min_qty': 'Ingano nkeya',
        'max_qty': 'Ingano nini',
        'all': 'Byose',
        'pick_date': 'Hitamo itariki',
        'clear_date': 'Siba itariki',
        'optional': 'bidahatirwa',

        // Shared
        'loading': 'Biratunganywa...',
        'error': 'Ikosa',
        'success': 'Byagenze neza',
        'yes': 'Yego',
        'no': 'Oya',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
